### ISSUE TITLE
DSL

### ISSUE THREAD

**Issue by padarom** [padarom/nucleus#1]
```yaml
pack: Minecraft
flavor: Vanilla
description: This is a vanilla Minecraft server
options:
  maxPlayers:
    type: int
    default: 20
  thingyoftheday: string
files:
  server.properties:
    type: ini
    options:
      - maxPlayers
      - motd: thingyoftheday
```
